[TASK] Introduce functional tests
TYPO3-Documentation/blog_example pull request #106
Opened 2024-05-23 17:25 UTC by linawolf

2024-05-24 17:55 UTC, froemken requested changes

2024-05-25 05:59 UTC, linawolf commented on Tests/Functional/Domain/Repository/PostRepositoryTest.php
> +namespace T3docs\blog_example\Tests\Functional\Domain\Repository;
Woops, good catch!

2024-05-25 06:03 UTC, linawolf commented
Thanks a lot for your contributions! However I would like to keep  the changes suggested to the runtests.sh suggested by @sbuerk , so I will revert these changes.

2024-05-25 06:12 UTC, linawolf commented on Build/php-cs-fixer/config.php
> +/*
I dont think we need theser disclaimer in configuration files or TCA. Should be enough to put them in classes?

2024-05-25 15:40 UTC, sbuerk commented
@froemken @linawolf 

I added a dedicated pull-request introducing generic
unit and functional testing infrastructure, so this
can be kept for now and @froemken extract his other
changes, for example cgl and configuration file places
in a dedicated change/pull-request.

See [#108 [TASK] Introduce unit and functional testing infrastructure](https://github.com/TYPO3-Documentation/blog_example/pull/108)

2024-05-30 08:23 UTC, linawolf commented
@froemken I think I moved most of your changes in separate PRs and merged them. About the remaining changes I am not so sure.
While your phpstorm.meta file looks interesting and I will try it out I think it is related to one special IDE and not at all to this project. So that would be another thing we had to test and maintain. So it does not really belong in this extension. You can keep one locally if you want.

Also I am reculant to spread the copy right information all over all PHP files. We display these files by automatic inclusion in the docs and it would blow up the docs.. I would rather just include a general LICENSE file or some such..

Can you check what else is still missing from your PR?

2024-05-31 21:57 UTC, closed without merging