[TASK] Refactor Backend Controller
TYPO3-Documentation/blog_example pull request #122
Opened 2024-05-31 19:53 UTC by linawolf

Redirect to index action if blog is not found

Show flash message when blog was deleted

Extract popoulate button to its own method

2024-05-31 20:11 UTC, froemken requested changes

2024-05-31 20:11 UTC, froemken commented on Classes/Controller/BackendController.php
> +    public function addPoppulateButton(ButtonBar $buttonBar): void
```suggestion
    public function addPopulateButton(ButtonBar $buttonBar): void
```

2024-05-31 20:11 UTC, froemken commented on Classes/Controller/BackendController.php
> +     */
Since strict types most of the annotations can be removed, except they contain additional information on how to use a variable or what else it contains
```suggestion
```

2024-05-31 20:11 UTC, froemken commented on Classes/Controller/BackendController.php
> +        $this->addPoppulateButton($buttonBar);
```suggestion
        $this->addPopulateButton($buttonBar);
```

2024-06-01 03:35 UTC, linawolf commented on Classes/Controller/BackendController.php
> +     */
yeah, phpstorm somethimes adds them and I miss removing ;)

2024-06-01 05:06 UTC, froemken approved these changes

2024-06-01 06:46 UTC, merged