Fix Service.yaml for type converter example
TYPO3-Documentation/blog_example pull request #41
Opened 2022-10-07 21:47 UTC by linawolf

2022-10-08 16:24 UTC, linawolf commented
Could you maybe review this @froemken? I can give you the necessary right.

2022-10-09 01:39 UTC, froemken requested changes

2022-10-09 01:39 UTC, froemken commented on CHANGELOG.md
> +- Fix Service.yaml for type converter example (#41)
Services.yaml

2022-10-09 07:23 UTC, linawolf commented on CHANGELOG.md
> +- Fix Service.yaml for type converter example (#41)
```suggestion
- Fix `Services.yaml` for type converter example (#41)
```

2022-10-09 13:46 UTC, froemken approved these changes

2022-10-09 13:50 UTC, merged